# Generated by Django 2.1.2 on 2018-10-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('estado', models.CharField(choices=[('Adoptado', 'Adoptado'), ('Disponible', 'Disponible'), ('Rescatado', 'Rescatado')], max_length=20)),
                ('imagen', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
