# Generated by Django 2.1.2 on 2018-10-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_perros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perros',
            name='imagen',
        ),
    ]
